### ISSUE TITLE
Default of DOCKER_COMPOSE_CMD should be golang version

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/devops#76]
Zhe Yan reported on the LF Edge open-horizon-mgmt-hub channel (on matrix chat svr) that on his Ubuntu 18.04.3 LTS on x86 machine, docker-compose is panicking:

```
~# curl -sSL https://raw.githubusercontent.com/open-horizon/devops/master/mgmt-hub/deploy-mgmt-hub.sh | bash
Management hub services will listen on http://127.0.0.1
Updating apt-get package index...
Installing prerequisites, this could take a minute...
----------- Downloading template files...
Substituting environment variables into template files...
----------- Downloading/starting Horizon management hub services...
Downloading management hub docker images...
Pulling openhorizon/amd64_agbot:latest ...
Pulling openhorizon/amd64_exchange-api:latest ...
Pulling openhorizon/amd64_cloud-sync-service:latest ...
Pulling postgres:latest ...
Pulling mongo:latest ...
Pulling openhorizon/sdo-owner-services:latest ...
Starting management hub containers...
Traceback (most recent call last):
File "urllib3/connectionpool.py", line 677, in urlopen
File "urllib3/connectionpool.py", line 392, in _make_request
File "http/client.py", line 1277, in request
File "http/client.py", line 1323, in _send_request
File "http/client.py", line 1272, in endheaders
...
```

The python version of docker-compose is only supposed to be used on `ppc64le`, but in some corner cases the DOCKER_COMPOSE_CMD variable gets set incorrectly.

**Comment by bmpotter** [comment]
Tested this myself, because no one else available.
